### ISSUE TITLE
Support splitting key-value stores by pre-specified splits

### ISSUE THREAD

**Issue by gabbard** [isi-vista/vistautils#120]
For example, to split it according to a standard train/test/dev split.

This would add a new parameter namespace `explicit_split` to `split_key_value_source.py`.  If specified, the parameters in this namespace would themselves be namespaces with two keys: the input key list file and the output key-value store path for that split.  

For example,

```
explicit_split:  
   train:
      keys_file: /path/to/train/keys
      output_file: /path/to/output.zip
   dev:
      keys_file: /path/to/dev/keys
      output_file: /path/to/dev-output.zip
```
